#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 24 18:55:35 2022

@author: huanghongru
"""

import time
import random
import requests
import datetime
import numpy as np
import pandas as pd
from dateutil import rrule
import re
import os
from datetime import date,timedelta

crawl_head = 0
crawl_tail = 946

def get_stock_list():
    res = requests.get("https://isin.twse.com.tw/isin/class_main.jsp?owncode=&stockname=&isincode=&market=1&issuetype=1&industry_code=&Page=1&chklike=Y")
    df = pd.read_html(res.text)[0]
    df = df.drop([0,1,4,5,8,9],axis = 1)
    df.columns = df.iloc[0]
    df = df.iloc[1:]
    return df

def get_monthly_stock_history(date, stock_no):
  
    url = 'http://www.twse.com.tw/exchangeReport/STOCK_DAY?date=%s&stockNo=%s' % ( date, stock_no)
    r = requests.get(url)
    data = r.json()
    if data['stat'] == 'OK':
        df = pd.DataFrame(data['data'], columns = data['fields'])
        df['股票代號'] = stock_no
        df['月份'] = date[4:6]
        return df
    else:
        print('Request Failed!! Stat:', data['stat'])

def create_date_list(start_date):
    date_list = []

    b_month = date(*[int(x) for x in start_date.split('/')])
    now = datetime.datetime.now().strftime('%Y/%m/%d')         # 取得現在時間
    e_month = date(*[int(x) for x in now.split('/')])
    
    for dt in rrule.rrule(rrule.MONTHLY, dtstart=b_month, until=e_month):
        file_date = re.compile(r'\d\d\d\d-\d\d')
        raw_date_list = file_date.findall(str(dt))
        date_str = raw_date_list[0]
        month_begin = date_str[0:4] + date_str[5:8] + '01'
        date_list.append(month_begin)
        
    return date_list


taiwan_stock = get_stock_list()

for i in range(crawl_head, crawl_tail):
    result = pd.DataFrame()
    release_date = taiwan_stock.iloc[i]['公開發行/上市(櫃)/發行日']
    if int(release_date.split('/')[0]) < 2012:
        begin_date = '2012/01/01'
    else:
        begin_date = release_date
    
    date_list = create_date_list(begin_date)
    
    #檔案路徑
    path = '/Users/huanghongru/Desktop/crawler/stock_price/' + taiwan_stock.iloc[i]['有價證券代號'] + '/'
    
    current_month = datetime.datetime.now().strftime('%Y-%m')
    latest_file = taiwan_stock.iloc[i]['有價證券代號'] + '-' + str(current_month) + '.csv'
    
  
    for d in date_list:
        #加快更新速度
        if os.path.isfile(path + latest_file):
            print('Updated to Latest:', taiwan_stock.iloc[i]['有價證券代號'])
            break
        
        #檔名
        file_name = taiwan_stock.iloc[i]['有價證券代號'] + '-' + str(d)[0:4] + '-' + str(d)[4:6] + '.csv'
        file_path = path + file_name

        if os.path.isfile(file_path):
            print('Have been downloaded:', i, taiwan_stock.iloc[i]['有價證券代號'], 'Date:', d)
        else:
            print('Processing:', i, 'Stock No.', taiwan_stock.iloc[i]['有價證券代號'], 'Date:', d)
            result = pd.concat([result, get_monthly_stock_history(d, taiwan_stock.iloc[i]['有價證券代號'])], axis=0)
            #print(result)
        
            result.to_csv(file_path)
        
            time.sleep(random.randint(5,10))